### ISSUE TITLE
Recover upstream PRs

### ISSUE THREAD

**Issue by ybasket** [scalafreaks/odin#34]
The `valskalla/odin` repo has a few PRs that would be nice to get into the fork:

- [x] https://github.com/valskalla/odin/pull/504
- [x] https://github.com/valskalla/odin/pull/461
- [x] https://github.com/valskalla/odin/pull/459

**Comment by aartigao** [comment]
These look easy implement 👀 

I'll see if I have some spare time soon to address them. But feel free to take some if you want 👍🏽

**Comment by aartigao** [comment]
Speaking of https://github.com/valskalla/odin/pull/504, I think the current `unsafeRunSync` approach does the right thing, for the general use case.

If `unsafeRunAndForget` is used, logger method invocation will return immediately, without any guarantee that log was actually materialized (see this [run](https://github.com/scalafreaks/odin/actions/runs/10295658746) for proof).

If someone wants to achieve fast performance without thread starvation, it should be using an `AsyncLogger` (possibly combined with `Dispatcher.parallel` if ordering doesn't matter).
