### ISSUE TITLE
Scala Steward artifact migration

### ISSUE THREAD

**Issue by ybasket** [scalafreaks/odin#44]
Scala Steward can update artifacts that are published on new group IDs if set up with a mapping, see https://github.com/scala-steward-org/scala-steward/blob/main/docs/artifact-migrations.md.

I'm not sure how the policy handles forks (if at all), but given that the upstream Odin repo seems quite dead despite my attempts to save it, I think it would be good for Odin's existing user base to get automatic update PRs for releases of this fork. Best to explain this situation transparently on the PR for Scala Steward, so the Steward maintainers can decide. Users can still choose to ignore this fork and close the PR.

**Comment by aartigao** [comment]
Thanks for sharing! ❤️ 

I'll create the PRs there and hope they understand the situation 🤞🏽

I hope this migration is applied soon, before releasing 0.15.0. I think it's time given the improvements merged.
